swagger: '2.0'
info:
  description: Simplified API for ticket reporting.
  version: 0.0.1
  title: Ticket Reports
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: cmcgovern@axway.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /api
tags:
  - name: jira
    description: Our Jira execution tickets
  - name: prodpad
    description: Our prodpad product ideas
schemes:
  - http
paths:
  '/jiraticket/{key}':
    get:
      tags:
        - jira
      summary: Get details of a Jira ticket
      description: Returns a single Jira ticket by key
      operationId: getJiraTicketById
      produces:
        - application/json
      parameters:
        - name: key
          in: path
          description: ID of pet to return
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/JiraTicket'
        '400':
          description: Invalid Key supplied
        '404':
          description: Jira ticket not found
      security:
        - api_key: []
      x-flow: ticketReports-getJiraTicketById
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  JiraTicket:
    type: object
    required:
      - key
    properties:
      key:
        type: string
      fixVersions:
        type: string
      created:
        type: string
      resolutionDate:
        type: string
      story_points:
        type: number
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
